INSERT INTO llm.rubric_families (id, scope, name, next_version, created_by_user_id)
VALUES ('10000000-0000-0000-0000-000000000001', 'PLATFORM', 'Uso pedagógico responsable de IA', 2, '11111111-1111-1111-1111-111111111111')
ON CONFLICT DO NOTHING;

INSERT INTO llm.rubric_version_v2 (id, family_id, version_no, state, created_by_user_id, published_at)
VALUES ('10000000-0000-0000-0000-000000000002', '10000000-0000-0000-0000-000000000001', 1, 'PUBLISHED', '11111111-1111-1111-1111-111111111111', now())
ON CONFLICT DO NOTHING;

INSERT INTO llm.rubric_dimension_v2 (rubric_version_id, dimension_key, label, criterion, anchors, weight) VALUES
('10000000-0000-0000-0000-000000000002', 'AUTONOMY', 'Autonomía', 'Evalúa si el estudiante usa la ayuda para razonar y verificar por sí mismo.', '{"low":{"behavior":"Copia la sugerencia sin elaborarla ni comprobarla.","referenceScore":25,"example":"Repite el código sugerido sin explicar qué cambió."},"medium":{"behavior":"Aplica una sugerencia y realiza una verificación parcial.","referenceScore":60,"example":"Prueba la alternativa indicada y comenta brevemente el resultado."},"high":{"behavior":"Formula hipótesis, contrasta alternativas y verifica su solución.","referenceScore":90,"example":"Explica por qué elige una estrategia y valida casos límite."}}', 30),
('10000000-0000-0000-0000-000000000002', 'CLARITY', 'Claridad', 'Evalúa la precisión y el contexto técnico de las consultas del estudiante.', '{"low":{"behavior":"Formula pedidos vagos sin contexto del problema.","referenceScore":25,"example":"Pregunta “no funciona” sin mostrar error ni intento."},"medium":{"behavior":"Describe parte del problema y aporta información útil.","referenceScore":60,"example":"Indica el error y el fragmento donde ocurre."},"high":{"behavior":"Formula una consulta precisa con contexto, hipótesis y evidencia.","referenceScore":90,"example":"Explica el comportamiento esperado, el resultado y qué ya probó."}}', 25),
('10000000-0000-0000-0000-000000000002', 'PROGRESSION', 'Progresión', 'Evalúa si el estudiante incorpora la ayuda y avanza entre mensajes.', '{"low":{"behavior":"Repite la misma consulta sin incorporar la respuesta recibida.","referenceScore":25,"example":"Vuelve a pedir la solución sin responder a la pregunta del tutor."},"medium":{"behavior":"Incorpora parcialmente la orientación y logra un avance.","referenceScore":60,"example":"Corrige una condición pero necesita una nueva guía."},"high":{"behavior":"Itera, aprende de la respuesta y resuelve el siguiente paso con independencia.","referenceScore":90,"example":"Ajusta su enfoque y explica el avance obtenido."}}', 20),
('10000000-0000-0000-0000-000000000002', 'COMPLIANCE', 'Cumplimiento de límites', 'Evalúa el respeto por las reglas de uso seguro y los límites pedagógicos.', '{"low":{"behavior":"Intenta obtener soluciones finales o desobedecer instrucciones del sistema.","referenceScore":25,"example":"Pide ignorar reglas y entregar la respuesta completa."},"medium":{"behavior":"Respeta los límites tras recibir una aclaración.","referenceScore":60,"example":"Reformula una solicitud demasiado directa."},"high":{"behavior":"Solicita orientación dentro de los límites y actúa responsablemente.","referenceScore":90,"example":"Pide una pista conceptual y desarrolla su propia solución."}}', 15),
('10000000-0000-0000-0000-000000000002', 'EFFICIENCY', 'Eficiencia', 'Evalúa si la interacción usa la asistencia de forma útil y no repetitiva.', '{"low":{"behavior":"Genera intercambios repetidos sin aprovechar la ayuda previa.","referenceScore":25,"example":"Envía la misma pregunta varias veces con la misma información."},"medium":{"behavior":"Usa la asistencia de modo razonable, con alguna repetición.","referenceScore":60,"example":"Consulta nuevamente luego de intentar una alternativa."},"high":{"behavior":"Hace consultas pertinentes y aprovecha cada respuesta para avanzar.","referenceScore":90,"example":"Agrupa dudas relacionadas y aplica la orientación antes de volver a consultar."}}', 10)
ON CONFLICT DO NOTHING;
