import { HttpClient, httpResource } from '@angular/common/http';
import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { catchError, finalize, of } from 'rxjs';
import { ToastService } from '../toast.service';
@Component({selector:'app-llm-settings-page',imports:[ReactiveFormsModule],changeDetection:ChangeDetectionStrategy.OnPush,templateUrl:'./llm-settings-page.component.html',styleUrl:'./llm-settings-page.component.scss'})
export class LlmSettingsPage {
 private readonly http=inject(HttpClient);private readonly fb=inject(FormBuilder);private readonly toast=inject(ToastService);
 readonly credentials=httpResource<Page<Credential>>(()=>'/api/llm/admin/provider-credentials',{defaultValue:{items:[]}});readonly candidates=httpResource<Page<Deployment>>(()=>'/api/llm/admin/evaluator-models',{defaultValue:{items:[]}});readonly active=httpResource<Deployment>(()=>'/api/llm/admin/evaluator-models/active');
 readonly form=this.fb.nonNullable.group({provider:['OPENAI_COMPATIBLE',Validators.required],name:['',Validators.required],baseUrl:['https://api.groq.com/openai/v1'],apiKey:['',[Validators.required,Validators.minLength(8)]]});readonly credentialId=signal('');readonly models=signal<string[]>([]);readonly model=signal('');readonly modelTested=signal(false);readonly selectedId=signal('');readonly message=signal('');readonly messages=signal<ChatMessage[]>([]);readonly busy=signal(false);
 readonly slots=computed(()=>[1,2,3].map(slot=>({slot,candidate:this.candidates.value().items.find(item=>item.candidateSlot===slot)??null})));readonly selected=computed(()=>this.candidates.value().items.find(item=>item.id===this.selectedId())??null);
 saveCredential(){if(this.form.invalid){this.toast.error('Completá los datos de la credencial.');return;}this.busy.set(true);this.http.post<Credential>('/api/llm/admin/provider-credentials',this.form.getRawValue()).pipe(finalize(()=>this.busy.set(false)),catchError(e=>{this.toast.error(detail(e,'No se pudo guardar la credencial.'));return of(null);})).subscribe(saved=>{if(saved){this.credentialId.set(saved.id);this.form.controls.apiKey.reset();this.credentials.reload();this.discover(saved.id);this.toast.success('Credencial cifrada y guardada.');}});}
 discover(id:string){this.credentialId.set(id);this.modelTested.set(false);this.busy.set(true);this.http.post<Page<string>>(`/api/llm/admin/provider-credentials/${id}/test`,{}).pipe(finalize(()=>this.busy.set(false)),catchError(e=>{this.toast.error(detail(e,'No se pudo conectar con el proveedor.'));return of(null);})).subscribe(r=>{if(r){this.models.set(r.items);this.toast.success(`${r.items.length} modelos disponibles.`);}});}
 testModel(){if(!this.credentialId()||!this.model()){this.toast.error('Elegí una credencial y un modelo.');return;}this.busy.set(true);this.http.post(`/api/llm/admin/provider-credentials/${this.credentialId()}/test-model`,{modelId:this.model()}).pipe(finalize(()=>this.busy.set(false)),catchError(e=>{this.toast.error(detail(e,'El modelo no respondió la prueba.'));return of(null);})).subscribe(result=>{if(result){this.modelTested.set(true);this.toast.success('Modelo conectado y listo para asignar.');}});}
 add(slot:number){if(!this.credentialId()||!this.model()||!this.modelTested()){this.toast.error('Probá la conexión del modelo antes de asignarlo.');return;}this.busy.set(true);this.http.post<Deployment>(`/api/llm/admin/provider-credentials/${this.credentialId()}/deployments`,{modelId:this.model(),slot}).pipe(finalize(()=>this.busy.set(false)),catchError(e=>{this.toast.error(detail(e,'No se pudo guardar el candidato.'));return of(null);})).subscribe(c=>{if(c){this.selectedId.set(c.id);this.messages.set([]);this.candidates.reload();this.toast.success(`Modelo asignado a tarjeta ${slot}. Probalo en el chat.`);}});}
 select(c:Deployment){this.selectedId.set(c.id);this.messages.set([]);} remove(c:Deployment){this.http.delete(`/api/llm/admin/evaluator-models/${c.id}`).pipe(catchError(e=>{this.toast.error(detail(e,'No se pudo archivar el candidato.'));return of(null);})).subscribe(()=>{this.candidates.reload();if(this.selectedId()===c.id)this.selectedId.set('');this.toast.success('Candidato archivado.');});}
 async send(event?: SubmitEvent){event?.preventDefault();const c=this.selected(),text=this.message().trim();if(!c||!text){this.toast.error('Elegí una tarjeta e ingresá un mensaje.');return;}this.busy.set(true);this.message.set('');this.messages.update(all=>[...all,{role:'user',text},{role:'assistant',text:''}]);try{const r=await fetch(`/api/llm/admin/evaluator-models/${c.id}/chat/stream`,{method:'POST',headers:{'Content-Type':'application/json','Accept':'text/event-stream'},body:JSON.stringify({message:text})});if(!r.ok||!r.body)throw new Error();const reader=r.body.getReader(),decoder=new TextDecoder();let buffer='';while(true){const chunk=await reader.read();if(chunk.done)break;buffer+=decoder.decode(chunk.value,{stream:true});const frames=buffer.split('\n\n');buffer=frames.pop()??'';for(const frame of frames)this.consume(frame);}this.candidates.reload();this.toast.success('Respuesta recibida: candidato validado.');}catch{this.toast.error('No se pudo completar la respuesta del modelo.');}finally{this.busy.set(false);}}
 activate(c:Deployment){this.busy.set(true);this.http.post<Deployment>(`/api/llm/admin/evaluator-models/${c.id}/activate`,{}).pipe(finalize(()=>this.busy.set(false)),catchError(e=>{this.toast.error(detail(e,'Probá el chat antes de activar el candidato.'));return of(null);})).subscribe(active=>{if(active){this.active.reload();this.candidates.reload();this.toast.success(`${active.modelId} es el evaluador global.`);}});}
 private consume(frame:string){const event=frame.match(/^event:\s*(.+)$/m)?.[1],data=frame.match(/^data:(.*)$/m)?.[1]?.trim()??'';if(event==='delta')this.messages.update(all=>all.map((x,i)=>i===all.length-1?{...x,text:x.text+data}:x));if(event==='error')this.toast.error(data);}
}
function detail(e:any,fallback:string){return e?.error?.detail??fallback;} interface Page<T>{items:T[];}interface Credential{id:string;displayName:string;provider:string;mask:string;}interface Deployment{id:string;provider:string;credentialName:string;modelId:string;state:string;candidateSlot:number;chatVerifiedAt?:string|null;}interface ChatMessage{role:'user'|'assistant';text:string;}
