package ar.edu.utn.frc.tup.piv.llm.infrastructure.persistence;
import com.fasterxml.jackson.databind.JsonNode; import java.util.*; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Repository;
@Repository public class GoldenSetImportRepository {
 private final JdbcTemplate jdbc; public GoldenSetImportRepository(JdbcTemplate j){jdbc=j;}
 public Optional<ImportBatch> create(UUID c,UUID v,String f,UUID k,UUID a,List<JsonNode> rows){UUID id=UUID.randomUUID();int n=jdbc.update("insert into llm.import_batches (id,course_id,golden_set_version_id,format,idempotency_key,created_by_user_id) select ?,?,?,?,?,? where exists (select 1 from llm.golden_set_versions v join llm.golden_set_families g on g.id=v.family_id where v.id=? and v.state='DRAFT' and g.course_id=? and g.scope='COURSE')",id,c,v,f,k,a,v,c);if(n==0)return existing(c,k);for(int i=0;i<rows.size();i++)jdbc.update("insert into llm.import_rows (batch_id,row_number,payload) values (?,?,cast(? as jsonb))",id,i+1,rows.get(i).toString());return Optional.of(new ImportBatch(id,v,f,"DRAFT",rows.size()));}
 public Optional<ImportBatch> existing(UUID c,UUID k){return jdbc.query("select id,golden_set_version_id,format,state::text as state from llm.import_batches where course_id=? and idempotency_key=?",(r,n)->new ImportBatch(r.getObject("id",UUID.class),r.getObject("golden_set_version_id",UUID.class),r.getString("format"),r.getString("state"),0),c,k).stream().findFirst();}
 public List<ImportRow> rows(UUID c,UUID b){return jdbc.query("select r.row_number,r.payload::text as payload from llm.import_rows r join llm.import_batches b on b.id=r.batch_id where r.batch_id=? and b.course_id=? order by r.row_number",(r,n)->new ImportRow(r.getInt(1),r.getString(2)),b,c);}
 public boolean replaceRow(UUID c,UUID b,int r,JsonNode p){return jdbc.update("update llm.import_rows r set payload=cast(? as jsonb),state='INVALID',errors='[]'::jsonb from llm.import_batches b where r.batch_id=b.id and r.batch_id=? and r.row_number=? and b.course_id=? and b.state in ('DRAFT','FAILED')",p.toString(),b,r,c)==1;}
 public boolean beginValidation(UUID c,UUID b){return jdbc.update("update llm.import_batches set state='VALIDATING' where id=? and course_id=? and state in ('DRAFT','FAILED')",b,c)==1;}
 public void rowResult(UUID b,int r,boolean ok,String e){jdbc.update("update llm.import_rows set state=?,errors=cast(? as jsonb) where batch_id=? and row_number=?",ok?"VALID":"INVALID",e,b,r);}
 public void finishValidation(UUID b,boolean ok){jdbc.update("update llm.import_batches set state=? where id=? and state='VALIDATING'",ok?"READY":"FAILED",b);}
 public Optional<UUID> claimReady(UUID c,UUID b){return jdbc.query("update llm.import_batches set state='VALIDATING' where id=? and course_id=? and state='READY' and not exists (select 1 from llm.import_rows r where r.batch_id=? and r.state<>'VALID') returning golden_set_version_id",(r,n)->r.getObject(1,UUID.class),b,c,b).stream().findFirst();}
 public void insertCases(UUID b,UUID v){jdbc.update("insert into llm.golden_set_cases (golden_set_version_id,case_order,review_state,transcript,challenge_context,safe_metadata,author,reference_scores,score_justifications) select ?,coalesce((select max(case_order)+1 from llm.golden_set_cases where golden_set_version_id=?),0)+r.row_number-1,'REVIEWED',r.payload->'transcript',r.payload->'challengeContext',coalesce(r.payload->'metadata','{}'::jsonb),r.payload->>'author',r.payload->'referenceScores',coalesce(r.payload->'scoreJustifications','{}'::jsonb) from llm.import_rows r where r.batch_id=? order by r.row_number",v,v,b);}
 public void complete(UUID b){jdbc.update("update llm.import_batches set state='COMMITTED',committed_at=now() where id=? and state='VALIDATING'",b);}
 public record ImportBatch(UUID id,UUID goldenSetVersionId,String format,String state,int rows){} public record ImportRow(int rowNumber,String payload){}
}
