package ar.edu.utn.frc.tup.piv.llm.infrastructure.persistence;
import ar.edu.utn.frc.tup.piv.llm.application.CalibrationWorkflowService;
import ar.edu.utn.frc.tup.piv.llm.domain.CalibrationStateMachine.CalibrationState;
import java.util.*; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Repository; import ar.edu.utn.frc.tup.piv.llm.security.CallerIdentity;
@Repository public class JdbcCalibrationWorkflowStore implements CalibrationWorkflowService.CalibrationWorkflowStore {
 private final JdbcTemplate jdbc; private final AuditRepository audit; public JdbcCalibrationWorkflowStore(JdbcTemplate jdbc,AuditRepository audit){this.jdbc=jdbc;this.audit=audit;}
 public boolean transition(UUID id, CalibrationState from, CalibrationState to){return jdbc.update("update llm.calibration_runs set state=?, started_at=case when ?='RUNNING' then now() else started_at end, finished_at=case when ? in ('PASSED','FAILED','CANCELLED') then now() else finished_at end where id=? and state=?",to.name(),to.name(),to.name(),id,from.name())==1;}
 public boolean isPassed(UUID id){return Boolean.TRUE.equals(jdbc.queryForObject("select exists(select 1 from llm.calibration_runs where id=? and state='PASSED')",Boolean.class,id));}
 public boolean isPassed(UUID course,UUID id){return Boolean.TRUE.equals(jdbc.queryForObject("select exists(select 1 from llm.calibration_runs where id=? and course_id=? and state='PASSED')",Boolean.class,id,course));}
 public void activate(UUID course,UUID run,CallerIdentity actor){jdbc.update("insert into llm.active_calibrations(course_id,calibration_run_id,activated_by_user_id) values(?,?,?) on conflict(course_id) do update set calibration_run_id=excluded.calibration_run_id,activated_by_user_id=excluded.activated_by_user_id,activated_at=now()",course,run,actor.delegatedUserId());audit.record("calibration.activated","calibration-run",run,actor,"{\"courseId\":\""+course+"\"}");}
 public boolean hasValidCalibration(UUID challenge){return Boolean.TRUE.equals(jdbc.queryForObject("select exists(select 1 from llm.challenge_calibration_assignments a join llm.active_calibrations c on c.course_id=a.course_id and c.calibration_run_id=a.calibration_run_id where a.challenge_id=?)",Boolean.class,challenge));}
 public void enqueue(UUID attempt,UUID challenge,UUID key){jdbc.update("insert into llm.pending_evaluations(attempt_id,assignment_challenge_id,calibration_run_id,idempotency_key) select ?,a.challenge_id,a.calibration_run_id,? from llm.challenge_calibration_assignments a where a.challenge_id=? on conflict(attempt_id) do nothing",attempt,key,challenge);}
 public Optional<CalibrationWorkflowService.QueuedEvaluation> claimNextQueued(){var rows=jdbc.query("select p.id,p.assignment_challenge_id,p.calibration_run_id from llm.pending_evaluations p where p.state='QUEUED' order by p.queued_at for update skip locked limit 1",(rs,n)->new CalibrationWorkflowService.QueuedEvaluation(UUID.fromString(rs.getString(1)),UUID.fromString(rs.getString(2)),UUID.fromString(rs.getString(3))));return rows.stream().findFirst();}
 public boolean markRunning(UUID id){return jdbc.update("update llm.pending_evaluations set state='RUNNING',started_at=now() where id=? and state='QUEUED'",id)==1;}
}
